# Generated by Django 4.1.3 on 2022-12-04 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2022, 12, 4), verbose_name='Примьера в мире'),
        ),
    ]
